### ISSUE TITLE
Add dropped message detection to Firehose clients

### ISSUE THREAD

**Issue by bradgessler** [firehoseio/firehose#52]
The client can detect a gap in the `last_message_sequence` and fire a "messagedropped" callback. This callback could be used by end users to send dropped message telemetry to a metrics server or have the client fill in the gaps by accessing their web servers.

**Comment by bradgessler** [comment]
Change the client to call the `dropped` callback per message. e.g.:

```javascript
new Firehose.Consumer({
  dropped: function(sequence){
    console.log(sequence + "was dropped");
  }
})
```

**Comment by bakkdoor** [comment]
Merged into master. Closing.

**Comment by bakkdoor** [comment]
That code is buggy and I reverted that commit until I can figure out what's causing issues. I'll probably also need to rewrite those JS client tests, they didn't catch the error and I think they aren't working as intended.

**Comment by bradgessler** [comment]
Closing this issue here since we moved the JS to a different repo. Continue at https://github.com/firehoseio/js_client/issues/3.
