### ISSUE TITLE
Scaling and high availability

### ISSUE THREAD

**Issue by srbartlett** [firehoseio/firehose#63]
Curious to know how firehose.io can be scaled.

Can the `Producer` and `Consumer` be scaled across multiple compute instances behind a load balancer?

I've looked at the code but not 100% sure it is possible -- especially with regards to the `Consumer`.  
Any clarification would be appreciated.

**Comment by bradgessler** [comment]
The Firehose server itself is horizontally scalable. Its backed by Redis so you'd want to configure those to the HA and performance traits for your application.

Was their something in particular in the `Consumer` that you're concerned about from a scaling perspective?
